# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99259855a207a23ff71c128d0c446c466f4e6519d068993d3f2b00c63d387637b29719738d3143b0d484e30c0983a8c64789f72bc734d4d5514075dbb13d150f

test:
  secret_key_base: ffd215b5e1f8577246ce8275abdf10615d5af8097af33a284bb8f6e511f8add9f48cf30d650cf7f47824c6a7e5a053c53fbb5b913f79286ce1cd6802f8cea22b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
